# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build
    pool: 
     vmImage: ubuntu-latest
    continueOnError: false
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/target'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
  
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: current
        downloadType: single
        downloadPath: '$(System.ArtifactsDirectory)'
        artifactName: 'drop'
        
    - task: Bash@3
      inputs:
       targetType: inline
       script: |
         cd $(System.ArtifactsDirectory)
         pwd
         ls -la
         unzip ./drop/liquidbase-demo.zip -d liquidbase-demo
         sudo chmod -R 755 ./liquidbase-demo 
         cd ./liquidbase-demo
         ls -la ./lib
         java -jar "./lib/liquidbase-core-4.8.0.jar" -defaultsFile=./src/main/resources/liquidbase.properties update